"""Per-byte meaning for every HS3 CAN ID seen on this vehicle.

Each ID maps to eight (role, meaning) tuples.
role is one of: signal, const, pad, flag, mux, nm, uds, tcu, unverified
"""
from __future__ import annotations

def _pad(val: int = 0) -> tuple[str, str]:
    return ("pad", f"unused {val:02X}")


def _c(val: int, name: str) -> tuple[str, str]:
    return ("const", f"{name}={val:02X}")


def _s(name: str) -> tuple[str, str]:
    return ("signal", name)


def _f(name: str) -> tuple[str, str]:
    return ("flag", name)


def _u(name: str) -> tuple[str, str]:
    return ("unverified", name)


def _zeros() -> list[tuple[str, str]]:
    return [_pad(0)] * 8


BYTE_MAP: dict[int, list[tuple[str, str]]] = {
    0x07A: [
        _s("HV current 15-bit Motorola bits6-0 + B1; A=raw*0.05-750 (B0 bit7=1)"),
        _s("HV current low byte"),
        _f("Ford BattTrac flags bits7-2 (typically 0) + voltage high 2 bits; B2=02 => Vhi=2"),
        _s("HV pack voltage low; V=((B2&3)<<8|B3)*0.5"),
        _c(0xA3, "HV Vmax limit *2 = 326V"),
        _c(0x4C, "HV Vmin limit *2 = 152V"),
        _pad(0),
        _pad(0),
    ],
    0x084: [
        _c(0x00, "year unused (Ford GlblClkYr)"),
        _pad(0),
        _s("calendar day high (Ford GlblClkDay)"),
        _s("calendar day low"),
        _s("clock minute 0-59"),
        _s("clock second 0-59"),
        _s("clock hour 0-23"),
        _pad(0),
    ],
    0x100: [
        _s("BCM rolling auth token high"),
        _s("BCM rolling auth token low"),
        _f("token frame 20 typical / 10 less often"),
        _f("token status (04 vs 08)"),
        _f("token companion discrete 3F-9F (22 values across captures)"),
        _f("high nibble 5/9/D; low nibble always 0"),
        _s("slow monotonic counter ~110 s/LSB"),
        _f("bit7 ~50% alive toggle; low 5A-5E"),
    ],
    0x101: [
        _f("bit6 ICE / bit7 EV / bit3 ready; 00=off"),
        _f("brake/chassis flags (A8 typical)"),
        _pad(0),
        _f("status nibble field"),
        _f("bit7 brake switch; low bits 0x43 released / 0x83 pressed"),
        _f("companion flags (F9 typical)"),
        _f("flags C0 typical"),
        _f("E9 typical; EA EV-only (B0 EV=1 ICE=0); C7 parked"),
    ],
    0x102: [_f("00 typical / 08 rare")] + _zeros()[1:],
    0x103: [
        _s("accelerator high (0x80 idle)"),
        _s("accelerator low; pedal=(BE16-0x8000)/5.3 %"),
        _s("RPM high; ICE if >0xE0 / EV if E000"),
        _s("RPM low; RPM=(BE16-0xE000)*2"),
        _f("0xE0 powertrain live / 00 off"),
        _pad(0),
        _f("small ICE-related 04-06"),
        _s("high-rate 8-bit aliased ~1 Hz; 00 whenever B4=00 off"),
    ],
    0x104: [
        _s("2-bit alive counter 0-3 (wraps 3→0)"),
        _s("high-rate 8-bit aliased ~1 Hz; full 256 unique; Δ≈90/sample; not gated to 0 when B3=02"),
        _s("coolant C = raw-60"),
        _f("0xF6 live / 02 off"),
        _s("heat-soak analog 50-90; parked ~82-90, driving ~50-76 (not ambient)"),
        _f("live bit7 with B3/B6; BD/BE run / 3E off"),
        _f("0x20 live / 00 off"),
        _pad(0),
    ],
    0x105: [
        _s("hybrid mode E0 parked / E8 city / F8 highway"),
        _f("0xB0 typical live; 50/D0 parked variants"),
        _f("80 typical live / 40 / C0 parked"),
        _f("09 typical live / 08 00 parked"),
        _f("FF typical live / 00 parked"),
        _f("B2 typical live / 10 parked"),
        _f("64 city with E8 / 34 highway with F8 / 60 parked with E0"),
        _f("8C typical live / 08 parked (bit7 ready)"),
    ],
    0x106: [
        _s("brake demand high 2 bits + 0x80 baseline"),
        _s("brake demand low; pct=10bit/10.23"),
        _f("brake-cluster mode: 09/0A moving 16-bit analog, 0B/13/1B stop sentinels"),
        _s("cluster low; 09xx-0Axx moving, FE with sentinels 0BFE/13FE/1BFE"),
        _s("long accel high 2 bits + live 3E nibble; m/s2=((B4&3)<<8|B5)*0.035-17.9"),
        _s("long accel low (Ford 10-bit; B4=03 sleep)"),
        _s("12-bit analog high nibble + live D / sleep 0 (B6=0x0F iff B4=0x03)"),
        _s("12-bit analog low; raw=((B6&0xF)<<8)|B7; 0xFFE rest sentinel"),
    ],
    0x107: [
        _s("speed high; km/h=BE16*0.01"),
        _s("speed low"),
        _s("park latch 60=P E0=not-P (D/R/N all E0)"),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
    ],
    0x108: [
        _s("HV SOC % = raw*0.5"),
        _f("SOC companion (33 typical)"),
        _f("SOC companion (33 typical)"),
        _f("B3 status B0 vs 30"),
        _f("B4 status C3 typical"),
        _pad(0),
        _pad(0),
        _pad(0),
    ],
    0x109: [
        _s("odometer 24-bit BE km"),
        _s("odometer mid"),
        _s("odometer low"),
        _s("fuel accumulator high"),
        _s("fuel accumulator low"),
        _f("fuel-acc companion FF typical / FD FE 1F also seen"),
        _s("odo-cluster companion; ρ≈-0.96 vs odo on city drives; frozen on some highway logs; not CRC/XOR"),
        _f("odo trailer E0 typical / 00 rare"),
    ],
    0x10A: [
        _f("12 vs 11 ignition-adjacent"),
        _c(0x0C, "transaxle const"),
        _s("transaxle 39=P 08/09=not-P (08 includes R); 38 rare stop"),
        _f("transaxle status typical 6D"),
        _f("transaxle status typical 93"),
        _pad(0),
        _f("transaxle status typical E3"),
        _f("transaxle trailer 05 typical / 04 rare"),
    ],
    0x10C: [
        _s("component analog 40-153; soak continues when motor B6=0 (not coolant/ambient)"),
        _pad(0),
        _pad(0),
        _f("thermal live 02 / off 00"),
        _f("thermal live B0 / off 00"),
        _pad(0),
        _s("NOT motor temp; live 64-77 / off 0 with B3=02 B4=B0"),
        _f("B7 nibble 4-bit field (low nibble always 0)"),
    ],
    0x10E: [
        _s("ignition 17=ON; 03=OFF only if B7=00"),
        _s("slow analog with parked soak AD/D3 typical; ramps Δ±1 while driving; inverse-IAT ρ≈-0.81 morning, no °C scale"),
        _f("05 parked-drive / 95 moving / 00 off"),
        _s("slow analog; 00 ⇒ B6=00 (all logs); not km/h (hwy-1 stuck at F9 while speed 82-99)"),
        _f("bitfield; bit5=1 iff B7=A0 (all logs); other bits vary"),
        _f("bitfield; bit2=1 iff B7=A0 (same as B4 bit5, all logs)"),
        _s("8-bit analog; 00 whenever B3=00; parked typically E1-E3; not checksum/counter/LFSR"),
        _s("drive-active; 00 off / 20 drive / A0 alt-drive"),
    ],
    0x10F: [
        _s("high-rate 16-bit BE aliased ~1 Hz"),
        _s("high-rate 16-bit low"),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
    ],
    0x110: [
        _s("motor angle high extra"),
        _s("motor angle 16-bit BE wraps 0-65535"),
        _s("motor angle low"),
        _f("resolver valid bit7=1 (0x80); 00 rare"),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
    ],
    0x112: [
        _pad(0),
        _pad(0),
        _c(0x1F, "TCU motion header"),
        _c(0xFE, "TCU motion header"),
        _s("00 low speed / 03 moving"),
        _s("motion-gated analog; 00 iff B4=00, else 155-232 (saturates E8)"),
        _pad(0),
        _s("slow monotonic counter ~2 min/LSB"),
    ],
    0x113: [
        _pad(0),
        _s("this-trip fuel used; L=raw*0.1 (8-bit, max 25.5 L)"),
        _pad(0),
        _pad(0),
        _s("trip km high; km=BE16*0.1"),
        _s("trip km low"),
        _pad(0),
        _pad(0),
    ],
    0x118: [
        _s("ICE distance 24-bit BE *0.1 km"),
        _s("ICE distance mid"),
        _s("ICE distance low"),
        _s("this-drive ICE km high; km=BE16*0.1 (B3:B4; Δ matches lifetime ICE)"),
        _s("this-drive ICE km low"),
        _s("DTE high; km=BE16*0.1"),
        _s("DTE low"),
        _pad(0),
    ],
    0x11A: [
        _s("mux prefix C1=VIN ASCII chunks / C0=alt payload"),
        _s("VIN chunk index 00/01/02"),
        _s("VIN ASCII 0"),
        _s("VIN ASCII 1"),
        _s("VIN ASCII 2"),
        _s("VIN ASCII 3"),
        _s("VIN ASCII 4"),
        _s("VIN ASCII 5"),
    ],
    0x122: [_f("event/heartbeat 00/01; extra bits 80/60/E0/20/A0 during TCU cmd failures")] + _zeros()[1:],
    0x127: _zeros(),
    0x141: [
        _s("HV current gauge; A≈(raw-39)*24 (12-level; MAE ~12 A vs 0x07A)"),
        _s("rolls 0-255; MAP B1:B2 likely false (counter)"),
        _s("motor coil temp = B2-40 degC; r=0.999 MAE 0.22 vs OBD (134 samples)"),
        _s("temp-like analog 47-98; tracks B7 MAE~1.7 (not 0x104 coolant)"),
        _s("percent 0-100 raw (not OBD engine load or throttle)"),
        _s("bits7-6 2-bit field + bits5-0 analog always 0x1F-0x28 (all logs)"),
        _f("high nibble 0-F field; low nibble always 0"),
        _s("temp-like analog 40-98; tracks B3 MAE~1.7 (not 0x104 coolant)"),
    ],
    0x142: [
        _s("ambient C = raw-64"),
        _s("7-bit analog (bit0 always 0); SI unknown"),
        _s("64=EV 68=ICE"),
        _f("B3 5F/3F/9F status"),
        _c(0xFC, "climate trailer"),
        _pad(0),
        _pad(0),
        _pad(0),
    ],
    0x146: [
        _s("TCU cmd 0C lock 04 unlock 01 start 02 stop 00 idle"),
        _pad(0),
        _pad(0),
        _s("door/lock sequence"),
        _pad(0),
        _s("remote-start sequence (when cmd 01/02)"),
        _s("BCM token echo high"),
        _s("BCM token echo low"),
    ],
    0x147: [
        _f("22 idle-live / 21 other; pairs with B4"),
        _s("remote-start countdown high seconds"),
        _s("remote-start countdown low"),
        _f("00 idle / 70 during countdown"),
        _f("04 with B0=22 / 02 with B0=21 / 84 during countdown"),
        _f("20/A0/80/60/00 status"),
        _pad(0),
        _pad(0),
    ],
    0x152: _zeros(),
    0x153: [
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
        _s("trip avg L/100km (from 0.1 US mpg BE)"),
        _s("trip avg L/100km low"),
        _c(0xB1, "economy trailer"),
        _c(0x8E, "economy trailer"),
    ],
    0x15E: [
        _s("mux index — see MUX_MAP"),
        ("mux", "mux payload"),
        ("mux", "mux payload"),
        ("mux", "mux payload"),
        ("mux", "mux payload"),
        ("mux", "mux payload"),
        ("mux", "mux payload"),
        ("mux", "mux payload"),
    ],
    0x172: _zeros(),
    0x173: _zeros(),
    0x174: [
        _pad(0),
        _s("fuel % high; % = BE16*0.1; 0 and 1000 invalid"),
        _s("fuel % low"),
        _f("bits0-1 always 11 sender-ok?; bit7 anti-slosh commit NOT lamp"),
        _f("fuel trailer B4 always 8E"),
        _f("fuel trailer B5 always 02"),
        _f("fuel trailer B6 session-stable"),
        _f("fuel trailer B7 session-stable unknown"),
    ],
    0x175: [
        _pad(0),
        _pad(0),
        _pad(0),
        _s("steer high; deg=(BE16-8192)*0.1"),
        _s("steer low"),
        _pad(0),
        _c(0x49, "steer trailer"),
        _pad(0),
    ],
    0x1B3: [
        _f("bit0 trunk ajar; bit1 rear fog; bit2 unlocked; bit6 in-motion"),
        _f("bit0 LEFT turn latch; bit1 left bulb flash; bit3 headlights; bits7-6 day(1)/night(2)"),
        _s("interior dimming; day/night dependent (84/08 dark, 14/04 + 11 daylight)"),
        _s("interior dimming level; pairs with B2"),
        _f("bit3 RIGHT turn cluster echo (lockstep with B7 bit7); with B1 bit1 = lock/unlock courtesy flash"),
        _s("ambient twilight level: 00 dark / 01 dawn-dusk / 05 daylight (NOT TCU presence)"),
        _f("bit0 RL ajar; bit1 RR ajar; bit6 LEFT turn cluster echo (lockstep with B1 bit1)"),
        _f("bit0 front fog; bit3 hood ajar; bit4 FR ajar; bit5 FL ajar; bit6 RIGHT turn latch; bit7 right bulb flash"),
    ],
    0x1B4: [
        _c(0x40, "BCM static"),
        _c(0x11, "BCM static"),
        _c(0x11, "BCM static"),
        _c(0xFF, "BCM static"),
        _c(0x23, "BCM static"),
        _c(0x23, "BCM static"),
        _pad(0),
        _pad(0),
    ],
    0x1B5: [
        _c(0x00, "TPMS FL status ok"),
        _s("TPMS FL bar = raw*0.01"),
        _f("TPMS FR status 00 ok / 01 set"),
        _s("TPMS FR bar = raw*0.01"),
        _c(0x00, "TPMS RL status ok"),
        _s("TPMS RL bar = raw*0.01"),
        _c(0x00, "TPMS RR status ok"),
        _s("TPMS RR bar = raw*0.01"),
    ],
    0x1B8: [
        _c(0xFF, "RCM readiness"),
        _c(0xFF, "RCM readiness"),
        _c(0xFF, "RCM readiness"),
        _c(0xFF, "RCM readiness"),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
    ],
    0x212: _zeros(),
    0x215: _zeros(),
    0x21E: _zeros(),
    0x22A: [
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
        _s("TcuCmd mark 00/01"),
        _s("TcuCmd mark 00/01"),
        _pad(0),
        _s("TcuCmd_Active 01=active"),
    ],
    0x232: _zeros(),
    0x246: [("uds", "ISO-TP/UDS")] * 8,
    0x24E: [("uds", "ISO-TP/UDS")] * 8,
    0x267: _zeros()[:4] + [_f("10 typical / 00 rare")] + _zeros()[5:],
    0x27B: _zeros(),
    0x27C: [
        _s("16=cmd / 00=idle"),
        _s("60=cmd / 0C=idle"),
        _pad(0),
        _s("TCU qualifier 12/F2/00/32 with cmd/idle"),
        _pad(0),
        _pad(0),
        _pad(0),
        _pad(0),
    ],
    0x27D: [_pad(0), _f("node extra 00/60/10/40/50"), _pad(0), _pad(0), _pad(0), _pad(0), _pad(0), _pad(0)],
    0x27E: [_f("00 typical / 20 also seen"), _c(0x02, "node descriptor"), _pad(0), _pad(0), _pad(0), _pad(0), _pad(0), _pad(0)],
    0x27F: [_pad(0), _c(0xF4, "offboard-charge descriptor"), _pad(0), _pad(0), _pad(0), _pad(0), _pad(0), _pad(0)],
    0x28A: [_pad(0), _pad(0), _pad(0), _pad(0), _pad(0), _c(0x02, "TCU schedule"), _c(0x01, "TCU schedule"), _pad(0)],
    0x28B: [_pad(0), _pad(0), _pad(0), _pad(0), _pad(0), _f("TCU send 21 vs 01"), _c(0x11, "TCU send"), _pad(0)],
    0x28D: [_pad(0), _pad(0), _c(0x01, "TCU static"), _pad(0), _pad(0), _pad(0), _pad(0), _pad(0)],
    0x28E: _zeros(),
    0x2B7: [("uds", "ISO-TP/UDS")] * 8,
    0x2BF: [("uds", "ISO-TP/UDS")] * 8,
    0x590: [
        _s("AUTOSAR NM source node 90=TCU"),
        _s("NM control bit vector"),
        _c(0xFF, "NM PNI/reserved"),
        _c(0xFF, "NM PNI/reserved"),
        _f("NM user data (FF vs 90)"),
        _f("NM user data (10/00/FF)"),
        _c(0xFF, "NM reserved"),
        _c(0xFF, "NM reserved"),
    ],
    0x59E: [
        _s("AUTOSAR NM source node 9E=GWM"),
        _s("NM control bit vector"),
        _c(0xFF, "NM reserved"),
        _c(0xFF, "NM reserved"),
        _f("NM user data"),
        _f("NM user data"),
        _c(0xFF, "NM reserved"),
        _c(0xFF, "NM reserved"),
    ],
    0x720: [("uds", "ISO-TP IPC request")] * 8,
    0x728: [("uds", "ISO-TP IPC response")] * 8,
    0x760: [("uds", "ISO-TP APIM request")] * 8,
    0x768: [("uds", "ISO-TP APIM response")] * 8,
    0x7DF: [("uds", "OBD functional request")] * 8,
    0x7E2: [("uds", "BECM physical request")] * 8,
    0x7E8: [("uds", "PCM physical response")] * 8,
    0x7EA: [("uds", "BECM physical response")] * 8,
}


# Per-mux 8-byte maps for 0x15E. Bytes marked unverified still need SI meaning.
_SCAN = [
    _s("mux index"),
    _s("scan analog sample (7-bit; bit0 always 0)"),
    _f("scan template 1A typical / 19 1B 1C"),
    _s("scan analog sample"),
    _s("scan analog sample"),
    _s("scan channel id (steps ~0x10 with mux 20-2E)"),
    _s("scan analog sample"),
    _pad(0),
]

MUX_MAP: dict[int, dict[int, list[tuple[str, str]]]] = {
    0x15E: {
        0x00: [
            _s("mux index"),
            _pad(0),
            _pad(0),
            _pad(0),
            _pad(0),
            _pad(0),
            _c(0xF2, "mux 00 marker (0C rare)"),
            _pad(0),
        ],
        0x01: [
            _s("mux index"),
            _f("clock companion 04/05"),
            _s("clock minute 0-59"),
            _s("clock second 0-59"),
            _c(0x09, "clock mux const"),
            _c(0x09, "clock mux const"),
            _c(0x0C, "clock mux const"),
            _pad(0),
        ],
        0x10: [
            _s("mux index"),
            _c(0x10, "static twin of mux 70"),
            _pad(0),
            _pad(0),
            _pad(0),
            _pad(0),
            _pad(0),
            _c(0x08, "static trailer"),
        ],
        0x16: [
            _s("mux index"),
            _s("GPS lat high"),
            _s("GPS lat low"),
            _s("GPS lat fine signed; deg += (B3-128)*1e-6 (MAE 8.6→6.0 m)"),
            _f("GPS 05 typical / 04 rare"),
            _s("GPS lon high"),
            _s("GPS lon low"),
            _f("high nibble 0-F field; low nibble always 8"),
        ],
        0x20: _SCAN,
        0x21: _SCAN,
        0x22: _SCAN,
        0x23: _SCAN,
        0x24: _SCAN,
        0x25: _SCAN,
        0x26: _SCAN,
        0x27: _SCAN,
        0x28: _SCAN,
        0x29: _SCAN,
        0x2A: _SCAN,
        0x2B: _SCAN,
        0x2C: _SCAN,
        0x2D: _SCAN,
        0x2E: _SCAN,
        0x30: [
            _s("mux index"),
            _s("4-bit field 0-15 (sat-count range; SI unproven)"),
            _s("GPS quality analog 00-47 (DOP-like)"),
            _s("GPS quality analog 00-21"),
            _s("GPS quality analog 00-3F (DOP-like)"),
            _c(0xFF, "mux 30 marker"),
            _pad(0),
            _pad(0),
        ],
        0x40: [
            _s("mux index"),
            _f("52 typical / 12 also / 00 rare"),
            _pad(0),
            _f("22 typical / 12 20 rare"),
            _s("7-bit analog (bit0 always 0); SI unknown"),
            _pad(0),
            _pad(0),
            _pad(0),
        ],
        0x70: [
            _s("mux index"),
            _c(0x10, "static twin of mux 10"),
            _pad(0),
            _pad(0),
            _pad(0),
            _pad(0),
            _pad(0),
            _c(0x08, "static trailer"),
        ],
        0x76: [
            _s("mux index"),
            _s("GPS lat high"),
            _s("GPS lat low"),
            _s("GPS lat fine signed; deg += (B3-128)*1e-6 (MAE 8.6→6.0 m)"),
            _f("GPS 05 typical / 04 rare"),
            _s("GPS lon high"),
            _s("GPS lon low"),
            _f("high nibble 0-F field; low nibble always 8"),
        ],
        0x86: [
            _s("mux index"),
            _s("GPS lat high"),
            _s("GPS lat low"),
            _s("GPS lat fine signed; deg += (B3-128)*1e-6 (MAE 8.6→6.0 m)"),
            _f("GPS 05 typical / 04 rare"),
            _s("GPS lon high"),
            _s("GPS lon low"),
            _f("high nibble 0-F field; low nibble always 8"),
        ],
    }
}


def unverified_bytes() -> list[tuple[int, int, str]]:
    out = []
    for cid, rows in BYTE_MAP.items():
        for i, (role, meaning) in enumerate(rows):
            if role == "unverified":
                out.append((cid, i, meaning))
    return out


def mux_unverified() -> list[tuple[int, int, int, str]]:
    out = []
    for cid, muxes in MUX_MAP.items():
        for mux, rows in muxes.items():
            for i, (role, meaning) in enumerate(rows):
                if role == "unverified":
                    out.append((cid, mux, i, meaning))
    return out
